//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentBill()
        {
            this.ServiceInBill = new HashSet<ServiceInBill>();
        }
    
        public int id { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<int> clientId { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> respEmployeeId { get; set; }
        public Nullable<int> bookingId { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceInBill> ServiceInBill { get; set; }
    }
}
