//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomPrice
    {
        public int id { get; set; }
        public Nullable<int> categoryId { get; set; }
        public string desc { get; set; }
        public decimal price { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
