//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceInBill
    {
        public int id { get; set; }
        public Nullable<int> billId { get; set; }
        public Nullable<int> seviceId { get; set; }
        public int amount { get; set; }
    
        public virtual PaymentBill PaymentBill { get; set; }
        public virtual Service Service { get; set; }
    }
}
